#!/usr/bin/perl -w

my $out = "cdoc";
my $in  = "src/cdoc";

my $js  = "tmp.js";
my $css = "tmp.css";

my $CSS_DATA = `cat $css`;
my $JS_DATA  = `cat $js`;

open IN,  "<$in";
open OUT, ">$out";

while (<IN>) {
	if ($_ eq "/* INSERT CSS */\n") {
		print OUT $CSS_DATA;
	} elsif ($_ eq "/* INSERT JS */\n") {
		print OUT $JS_DATA;
	} else {
		print OUT $_;
	}
}

close IN;
close OUT;
